### ISSUE TITLE
We can keep a sticky navbar instead of fixed one

### ISSUE THREAD

**Issue by vatsalshah041** [balaji-sivasakthi/InfoSense#1]

**Comment by balaji-sivasakthi** [comment]
Hi @vatsalshah041, I greatly appreciate your interest in the project. I need more details about your issue.

**Comment by sricharanandra** [comment]
![Git Pull _ Atlassian Git Tutorial - Brave 30-09-2023 15_47_57](https://github.com/balaji-sivasakthi/InfoSense/assets/114226379/51579f3c-d907-46d7-a4d3-85b6eedb9c5c)
![Git Pull _ Atlassian Git Tutorial - Brave 30-09-2023 15_47_59](https://github.com/balaji-sivasakthi/InfoSense/assets/114226379/c4698016-a021-45a5-91d4-83d6793092ba)

I think he means that the navbar is fixed in its place, instead of staying at the top of the screen when you scroll down. I can make it a sticky navbar, if you assign this issue to me

**Comment by vatsalshah041** [comment]
> Hi @vatsalshah041, I greatly appreciate your interest in the project. I need more details about your issue.

I mean to say if I scroll down I should still see the different contents of the site which I came on the navbar so for that the nav ar should be sticky

**Comment by balaji-sivasakthi** [comment]
@vatsalshah041 Can I assign this issue to him?

**Comment by sricharanandra** [comment]
@balaji-sivasakthi  I'll send a PR with the changes in a few hours.

**Comment by vatsalshah041** [comment]
> @vatsalshah041 Can I assign this issue to him?

i mean I raised the issue so if u can assign to me it would be helpful

**Comment by sricharanandra** [comment]
@vatsalshah041 I'll unassign myself since you are the one who raised this issue. You can have it.

**Comment by vatsalshah041** [comment]
> @vatsalshah041 I'll unassign myself since you are the one who raised this issue. You can have it.

Ooh..thank you so much🤝... @balaji-sivasakthi  can you assign it to me...I'll complete it by tonight

**Comment by sricharanandra** [comment]
@vatsalshah041 You don't need to be assigned to fix issue man. If no one is assigned, just do the work and make a PR

**Comment by vatsalshah041** [comment]
@balaji-sivasakthi i have done the chnaged and made a pull request so if u could check and emerge the pull request
